/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  gettingStartedSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/quickstart',
        'getting-started/basictutorial',
      ],
    },
  ],

  writeCodeSidebar: [
    {
      type: 'category',
      label: 'Write Code',
      items: [
        'write-code/bestpractices',
        'write-code/codingessentials',
      ],
    },
  ],

  deploySidebar: [
    {
      type: 'category',
      label: 'Deploy',
      items: [
        'deploy/bestpractices',
        'deploy/setup',
      ],
    },
  ],
  
};

export default sidebars;
